apiVersion: apps/v1
kind: Deployment
metadata:
  name: unattested
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unattested
  template:
    metadata:
      labels:
        app: unattested
    spec:
      serviceAccountName: default
      containers:
      - name: workload
        image: workload:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: psat
            mountPath: /var/run/secrets/tokens
            readOnly: true
      volumes:
        - name: psat
          projected:
            sources:
              - serviceAccountToken:
                  path: psat
                  audience: kubespiffed
                  expirationSeconds: 3600

