apiVersion: v1
kind: Service
metadata:
  name: kubespiffed
  namespace: kubespiffe
spec:
  selector:
    app: kubespiffed
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
